apiVersion: v1
kind: Pod
metadata: 
  name: kubia-gpu
spec:
  nodeSelector:
    gpi: "true"
  containers:
  - image: choialdrich/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP